### ISSUE TITLE
Touchegg client crashing on start due to symlink for configuration

### ISSUE THREAD

**Issue by iwismer** [JoseExposito/touchegg#409]
### Describe the bug

Touchegg client crashes on start with the error message:

`what():  filesystem error: cannot create directories: Not a directory [/home/isaac/.config/touchegg]`

I'm guessing that is is becuase I have `/home/isaac/.config/touchegg` set as a symlink:

`lrwxrwxrwx   38 isaac  4 Dec  9:46 touchegg -> ../.dotfiles/touchegg/.config/touchegg`

It worked fine on the last version of the touchegg AUR package (2.0.2??), but now doesn't work after I updated to 2.0.4, but I haven't noticed anything in the changelog that sticks out to me as the cause. I've also updated lots of other things on my system in the mean time, but I doubt they would affect this.

### Expected behaviour

Touchegg client starts without issue

### Actual behaviour

Touchegg client crashes every time you start it

### Your environment

 * Version: 2.0.4
 * Distro: Arch Linux (touchegg package from the AUR
 * Desktop Environment: KDE Plasma

**Comment by JoseExposito** [comment]
Thanks for the bug report! It's fixed now and it'll be release in 2.0.5. If you want to use it now, you can use the touchegg-git package from AUR.

**Comment by iwismer** [comment]
Amazing! Thank you so much!

**Comment by vaskark** [comment]
I'm having this problem as well. I just installed the 2.0.5 version and it is still happening for me. I'm on Ubuntu Groovy.
I'm using a group of scripts that changes the symlink based on the environment I'm logging into. One of the scripts looks like this:

```
#!/bin/sh

rm -f $HOME/.config/touchegg/touchegg.conf
ln -s $HOME/.config/touchegg/touchegg-berry.conf $HOME/.config/touchegg/touchegg.conf

killall -s USR1 touchegg
sleep 0.1s
touchegg &
```
This was working fine with 2.0.3, I believe. Anyhoo, just thought I'd report it.

**Comment by JoseExposito** [comment]
Hi @vaskark , thanks for your bug report. Could you create a different issue and attach the logs there please?
